import json

# 读取 JSON 格式的 cookies 文件
with open('cookies.json', 'r') as f:
    cookies = json.load(f)

# 创建 Netscape 格式的 cookies 文件
with open('cookies.txt', 'w') as f:
    f.write("# Netscape HTTP Cookie File\n")
    f.write("# http://curl.haxx.se/rfc/cookie_spec.html\n")
    f.write("# This file was generated by libcurl! Edit at your own risk.\n\n")
    
    for cookie in cookies:
        domain = cookie['domain']
        path = cookie['path']
        secure = 'TRUE' if cookie['secure'] else 'FALSE'
        httpOnly = 'TRUE' if cookie.get('httpOnly', False) else 'FALSE'
        expiration = str(int(cookie.get('expirationDate', 0)))  # 转换为整数
        name = cookie['name']
        value = cookie['value']
        
        # 写入 Netscape 格式
        f.write(f"{domain}\tTRUE\t{path}\t{secure}\t{expiration}\t{name}\t{value}\n")

print("Cookies 已转换为 Netscape 格式并保存为 cookies.txt")
